### ISSUE TITLE
Design / Style 

### ISSUE THREAD

**Issue by Kohze** [lgatto/2017-spatialmap-robin#6]
A page to collect the UI frameworks we can use and share screenshots of interesting references. 

- currently used: http://dev.office.com/fabric#/components
- released this week: http://fluent.microsoft.com/

since the new fluent design is still close to the fabric components, we could re-create the new "fluent" design with all their features. Fluent design seems to be a mix of the apple minimalistic design and material design, which seems quite convincing. 

Other react.js alternatives:
- Material UI: http://www.material-ui.com

More inspirations:
- https://site.uplabs.com/posts/c/resources/interface

**Comment by Kohze** [comment]
This might have HomePage potential: 
- https://site.uplabs.com/posts/australian-start-up-loan-comparison-calculator-ani

it would be realized with css3 animation events and probably should some parallax sliding (from a react.js component). Instead of the waves we could display something looking like a scatter plot (with many points).

**Comment by Kohze** [comment]
Another useful UI/UX page from Apple: 
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Strategies.html#//apple_ref/doc/uid/20000957-CH19-SW1

**Comment by lgatto** [comment]
I am generally not too keep on Microsoft's design, I find it too edgy. 

Before committing, we should probably design some mock-ups (by hand in a first instance is fine), to make sure we have the same things in mind.

**Comment by Kohze** [comment]
We probably should seperate the ui framework (like materialUI, fluent design etc.) from the mockup/structural ordering in our process, as every ui framework has in the end the same standard set of object options. 

I will finish structural mockups by sunday, while for the design itself we need to find a well implemented design language (rather can creating our own). The advantage of those design frameworks is that they often iterated through tens to hundreds of effects for every element to create a unified experience (while we can always change parts of it).  

-- i now moove this issue over to the SpatialMapDev.
